driver:
  name: vagrant
  cache_directory: false
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.4.19

verifier:
  name: inspec
  format: documentation
  inspec_tests:
    - workup_build/test

platforms:
  - name: macos
    driver:
      box: jhcook/osx-elcapitan-10.11
      network:
        - ["private_network", {ip: "192.168.33.33"}]
      synced_folders:
        - ['..', '/vagrant/code/workup', 'type: :nfs']

  - name: windows-i386
    driver:
      box: mwrock/Windows2016
      synced_folders:
        - ['..', '/Users/vagrant/workup']
    attributes:
      omnibus:
        build_user_group: Administrators

suites:
  - name: default
    run_list: workup_build::default
