# frozen_string_literal: true
source 'http://rubygems.org'

# Install omnibus
gem 'omnibus', git: 'https://github.com/chef/omnibus.git', branch: 'ksubrama/gcc_investigate'

# Use Chef's software definitions. It is recommended that you write your own
# software definitions, but you can clone/fork Chef's to get you started.
gem 'omnibus-software', git: 'https://github.com/chef/omnibus-software.git', branch: 'ksubrama/ruby23'

gem 'test-kitchen', '~> 1.15'
gem 'kitchen-vagrant', '~> 1.0'
gem 'kitchen-inspec'
gem 'berkshelf'
