source 'https://rubygems.org'

# Install omnibus

# Use Chef's software definitions. It is recommended that you write your own
# software definitions, but you can clone/fork Chef's to get you started.
gem 'omnibus-software', github: 'chef/omnibus-software'
