#!/bin/sh
#
# Perform necessary workup setup steps
# after package is installed.
#

PROGNAME=`basename $0`
INSTALLER_DIR=/opt/workup/embedded

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

is_darwin()
{
  uname -v | grep "^Darwin" 2>&1 >/dev/null
}

is_smartos()
{
  uname -v | grep "^joyent" 2>&1 >/dev/null
}

if is_smartos; then
    PREFIX="/opt/local"
elif is_darwin; then
    PREFIX="/usr/local"
    mkdir -p "$PREFIX/bin"
else
    PREFIX="/usr"
fi

# rm -f before ln -sf is required for solaris 9
rm -f $PREFIX/bin/workup
ln -sf $INSTALLER_DIR/bin/workup $PREFIX/bin || error_exit "Cannot link workup to $PREFIX/bin"


echo "Thank you for installing workup!"

exit 0
