name 'workup_build'
maintainer 'Morley, Jonathan'
maintainer_email 'JMorley@cvent.com'
license 'Copyright (c) 2015 Cvent Inc., All Rights Reserved.'
description 'Cookbook to build the workup omnibus packages'
long_description 'Cookbook to build the workup omnibus packages'
version '0.0.1'

depends 'omnibus'
depends 'rubyinstaller'
depends 'git'
